version: '3.5'

services:
#  jwt:
#    build: ./jwt
#    ports:
#      - 8081:8081
#      - 2345:2345
#    volumes:
#      - ./jwt:/app
#    security_opt:
#      - apparmor:unconfined
#    cap_add:
#      - SYS_PTRACE
#    command: ["realize", "start", "--run"]

  session:
    build: ./session
    ports:
      - 8089:8089
      - 23450:2345
    volumes:
      - ./session:/app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    command: ["realize", "start", "--run"]


  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./api.yaml:/usr/share/nginx/html/sample.yaml
    environment:
      API_URL: sample.yaml
    ports:
      - "8082:8080"