version: '3.5'

services:
  api:
    build: ./api
    ports:
      - 8081:8081
    volumes:
      - ./api:/app
    command: ["realize", "start", "--run"]

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./api.yaml:/usr/share/nginx/html/sample.yaml
    environment:
      API_URL: sample.yaml
    ports:
      - "8082:8080"